### ISSUE TITLE
[Behaviour] macos-tiling-wms.mdx: change layout to "tiling" to make shortcuts consistent with other open windows in the window manager

### ISSUE THREAD

**Issue by msharran** [ghostty-org/website#163]
## Problem

When using "floating" layout, new windows created using "cmd+n" don't recognise tiling commands like "alt+l" or "alt+h" to move it front or back. Only the first window created was being controlled like other tiling windows. It may be because floating windows aren't part of tiling tree. 

The same thing happened to me with Kitty when I started using it with aerospace and the following config tells aerospace to consider new windows to be part of tiling tree.

## Why?

When rest of the windows and applications are tiling and suddenly the newly created Ghostty window becomes floating, the shortcuts become inconsistent.

I feel this could be the sane defaults for aerospace.

## Proposed Configs

```toml
[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run = [ "layout tiling" ]
```

## My Configs

```toml
# my kitty conf
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['layout tiling' , 'move-node-to-workspace T']

# my ghostty conf
[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run = [ "layout tiling", 'move-node-to-workspace T' ]
```
